  language: python
  python:
    - "3.6"
  install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
  script:
    - cd ast_project_2018
    - coverage run test_cases.py
  after_success:
  - coveralls
